#ifndef SRC_TRACED_PROBES_TRACEALYZER_TRACE_EVENT_H_
#define SRC_TRACED_PROBES_TRACEALYZER_TRACE_EVENT_H_

#include <cstdint>

namespace perfetto {

namespace tracealyzer {

/* clang-format off */
#define EVENT_CODE() \
    X(TraceStart, 0x01) \
    X(TsConfig, 0x02) \
    X(ObjName, 0x03) \
    X(TaskPrioInherit, 0x05) \
    X(TaskPrioDisinherit, 0x06) \
    X(DefineIsr, 0x07) \
    X(ThreadSchedWakeup, 0xB6) \
    X(ThreadSchedAbort, 0x20) \
    X(ThreadSchedPrioritySet, 0x04) \
    X(ThreadSchedReady, 0x30) \
    X(ThreadSchedResume, 0x7C) \
    X(ThreadSchedSuspend, 0x7B) \
    X(ThreadForeachEnter, 0x09) \
    X(ThreadForeachExit, 0x0B) \
    X(ThreadForeachUnlockedEnter, 0x0A) \
    X(ThreadForeachUnlockedExit, 0xF2) \
    X(ThreadInit, 0x10) \
    X(ThreadUserModeEnter, 0x0C) \
    X(ThreadHeapAssign, 0xFC) \
    X(ThreadJoinSuccess, 0xB0) \
    X(ThreadJoinBlocking, 0xB2) \
    X(ThreadJoinTimeout, 0xB1) \
    X(ThreadSleepEnter, 0x2A) \
    X(ThreadSleepExit, 0x2B) \
    X(ThreadMsleepEnter, 0x2C) \
    X(ThreadMsleepExit, 0x2D) \
    X(ThreadUsleepEnter, 0x2E) \
    X(ThreadUsleepExit, 0x2F) \
    X(ThreadBusyWaitEnter, 0xB4) \
    X(ThreadBusyWaitExit, 0xF3) \
    X(ThreadYield, 0xB5) \
    X(ThreadWakeup, 0x15D) \
    X(ThreadAbort, 0x15E) \
    X(ThreadStart, 0xB3) \
    X(ThreadSetPriority, 0x15F) \
    X(ThreadSuspend, 0x161) \
    X(ThreadResume, 0x160) \
    X(ThreadSchedLock, 0xB7) \
    X(ThreadSchedUnlock, 0xB8) \
    X(WorkInit, 0x11E) \
    X(WorkSubmitToQueueSuccess, 0x11F) \
    X(WorkSubmitToQueueBlocking, 0x120) \
    X(WorkSubmitToQueueFailure, 0x121) \
    X(WorkSubmitSuccess, 0x122) \
    X(WorkSubmitBlocking, 0x123) \
    X(WorkSubmitFailure, 0x124) \
    X(WorkFlushSuccess, 0x125) \
    X(WorkFlushBlocking, 0x126) \
    X(WorkFlushFailure, 0x127) \
    X(WorkCancelSuccess, 0x128) \
    X(WorkCancelBlocking, 0x129) \
    X(WorkCancelFailure, 0x12A) \
    X(WorkCancelSyncSuccess, 0x12B) \
    X(WorkCancelSyncBlocking, 0x12C) \
    X(WorkCancelSyncFailure, 0x12D) \
    X(WorkQueueStartSuccess, 0x12E) \
    X(WorkQueueStartBlocking, 0x12F) \
    X(WorkQueueStartFailure, 0x130) \
    X(WorkQueueDrainSuccess, 0x131) \
    X(WorkQueueDrainBlocking, 0x132) \
    X(WorkQueueDrainFailure, 0x133) \
    X(WorkQueueUnplugSuccess, 0x134) \
    X(WorkQueueUnplugBlocking, 0x135) \
    X(WorkQueueUnplugFailure, 0x136) \
    X(DworkInit, 0x137) \
    X(DworkScheduleForQueueSuccess, 0x138) \
    X(DworkScheduleForQueueBlocking, 0x139) \
    X(DworkScheduleForQueueFailure, 0x13A) \
    X(DworkScheduleSuccess, 0x13B) \
    X(DworkScheduleBlocking, 0x13C) \
    X(DworkScheduleFailure, 0x13D) \
    X(DworkRescheduleForQueueSuccess, 0x13E) \
    X(DworkRescheduleForQueueBlocking, 0x13F) \
    X(DworkRescheduleForQueueFailure, 0x140) \
    X(DworkRescheduleSuccess, 0x141) \
    X(DworkRescheduleBlocking, 0x142) \
    X(DworkRescheduleFailure, 0x143) \
    X(DworkFlushSuccess, 0x144) \
    X(DworkFlushBlocking, 0x145) \
    X(DworkFlushFailure, 0x146) \
    X(DworkCancelDelayableSuccess, 0x147) \
    X(DworkCancelDelayableBlocking, 0x148) \
    X(DworkCancelDelayableFailure, 0x149) \
    X(DworkCancelDelayableSyncSuccess, 0x14A) \
    X(DworkCancelDelayableSyncBlocking, 0x14B) \
    X(DworkCancelDelayableSyncFailure, 0x14C) \
    X(UworkInit, 0x14D) \
    X(UworkSubmitToQueueSuccess, 0x14E) \
    X(UworkSubmitToQueueBlocking, 0x14F) \
    X(UworkSubmitToQueueFailure, 0x150) \
    X(UworkQueueStartEnter, 0x151) \
    X(UworkQueueStartExit, 0x152) \
    X(PworkInitEnter, 0x153) \
    X(PworkInitExit, 0x166) \
    X(PworkSubmitToQueueSuccess, 0x154) \
    X(PworkSubmitToQueueBlocking, 0x155) \
    X(PworkSubmitToQueueFailure, 0x156) \
    X(PworkSubmitSuccess, 0x157) \
    X(PworkSubmitBlocking, 0x158) \
    X(PworkSubmitFailure, 0x159) \
    X(PworkCancelSuccess, 0x15A) \
    X(PworkCancelBlocking, 0x15B) \
    X(PworkCancelFailure, 0x15C) \
    X(IsrEnter, 0x162) \
    X(IsrExit, 0x163) \
    X(IsrExitToScheduler, 0x164) \
    X(PollEventInit, 0x82) \
    X(PollPollSuccess, 0x8F) \
    X(PollPollBlocking, 0x11) \
    X(PollPollFailure, 0x0D) \
    X(PollSignalInit, 0x83) \
    X(PollSignalReset, 0x8D) \
    X(PollSignalCheck, 0xF0) \
    X(PollSignalRaiseSuccess, 0x8E) \
    X(PollSignalRaiseFailure, 0xEF) \
    X(QueueInit, 0xC0) \
    X(QueueCancelWait, 0xC1) \
    X(QueueQueueInsertSuccess, 0xBC) \
    X(QueueQueueInsertBlocking, 0xBD) \
    X(QueueQueueInsertFailure, 0xBE) \
    X(QueueAppend, 0xC2) \
    X(QueueAllocAppendSuccess, 0xC3) \
    X(QueueAllocAppendBlocking, 0xF1) \
    X(QueueAllocAppendFailure, 0xC4) \
    X(QueuePrepend, 0xC5) \
    X(QueueAllocPrependSuccess, 0xC6) \
    X(QueueAllocPrependBlocking, 0xBF) \
    X(QueueAllocPrependFailure, 0xC7) \
    X(QueueInsert, 0xC8) \
    X(QueueAppendListSuccess, 0xC9) \
    X(QueueAppendListBlocking, 0x165) \
    X(QueueAppendListFailure, 0xCA) \
    X(QueueMergeSlistSuccess, 0xCB) \
    X(QueueMergeSlistBlocking, 0x6E) \
    X(QueueMergeSlistFailure, 0xCC) \
    X(QueueGetSuccess, 0xCD) \
    X(QueueGetBlocking, 0xCE) \
    X(QueueGetTimeout, 0xCF) \
    X(QueueRemoveSuccess, 0xD0) \
    X(QueueRemoveBlocking, 0xDB) \
    X(QueueRemoveFailure, 0xD1) \
    X(QueueUniqueAppendSuccess, 0xD2) \
    X(QueueUniqueAppendBlocking, 0xEE) \
    X(QueueUniqueAppendFailure, 0xB9) \
    X(QueuePeekHead, 0xBA) \
    X(QueuePeekTail, 0xBB) \
    X(FifoInitEnter, 0x100) \
    X(FifoInitExit, 0x101) \
    X(FifoCancelWaitEnter, 0x102) \
    X(FifoCancelWaitExit, 0x103) \
    X(FifoPutEnter, 0x104) \
    X(FifoPutExit, 0x105) \
    X(FifoAllocPutSuccess, 0x106) \
    X(FifoAllocPutBlocking, 0x107) \
    X(FifoAllocPutFailure, 0x108) \
    X(FifoPutListEnter, 0x109) \
    X(FifoPutListExit, 0x10A) \
    X(FifoPutSlistEnter, 0x10B) \
    X(FifoPutSlistExit, 0x10C) \
    X(FifoGetSuccess, 0x10D) \
    X(FifoGetBlocking, 0x10E) \
    X(FifoGetFailure, 0x10F) \
    X(FifoPeekHeadEnter, 0x110) \
    X(FifoPeekHeadExit, 0x111) \
    X(FifoPeekTailEnter, 0x112) \
    X(FifoPeekTailExit, 0x113) \
    X(LifoInitEnter, 0x114) \
    X(LifoInitExit, 0x115) \
    X(LifoPutEnter, 0x116) \
    X(LifoPutExit, 0x117) \
    X(LifoAllocPutSuccess, 0x118) \
    X(LifoAllocPutBlocking, 0x119) \
    X(LifoAllocPutFailure, 0x11A) \
    X(LifoGetSuccess, 0x11B) \
    X(LifoGetBlocking, 0x11C) \
    X(LifoGetFailure, 0x11D) \
    X(StackInit, 0x4A) \
    X(StackAllocInitSuccess, 0x4B) \
    X(StackAllocInitBlocking, 0x4C) \
    X(StackAllocInitFailure, 0x4D) \
    X(StackCleanupSuccess, 0x4E) \
    X(StackCleanupBlocking, 0x4F) \
    X(StackCleanupFailure, 0x26) \
    X(StackPushSuccess, 0x27) \
    X(StackPushBlocking, 0x3E) \
    X(StackPushFailure, 0x3F) \
    X(StackPopSuccess, 0x5B) \
    X(StackPopBlocking, 0x5E) \
    X(StackPopFailure, 0x5F) \
    X(QueueCreate, 0x11) \
    X(MutexCreate, 0x13) \
    X(TimerCreate, 0x14) \
    X(EventgroupCreate, 0x15) \
    X(SemaphoreCreateSuccess, 0x16) \
    X(SemaphoreCreateTimeout, 0x12) \
    X(MutexRecursiveCreate, 0x17) \
    X(StreambufferCreate, 0x18) \
    X(MemorySlabInitSuccess, 0x1C) \
    X(MemorySlabInitFailure, 0x29) \
    X(KheapInit, 0x1D) \
    X(QueueDelete, 0x21) \
    X(SemaphoreDelete, 0x22) \
    X(MutexDelete, 0x23) \
    X(TimerDelete, 0x24) \
    X(EventgroupDelete, 0x25) \
    X(StreambufferDelete, 0x28) \
    X(NewTime, 0x31) \
    X(NewTimeSchedulerSuspended, 0x32) \
    X(IsrBegin, 0x33) \
    X(IsrResume, 0x34) \
    X(TsBegin, 0x35) \
    X(TsResume, 0x36) \
    X(TaskActivate, 0x37) \
    X(Malloc, 0x38) \
    X(Free, 0x39) \
    X(LowpowerBegin, 0x3A) \
    X(LowpowerEnd, 0x3B) \
    X(IfeNext, 0x3C) \
    X(IfeDirect, 0x3D) \
    X(TaskCreateFailed, 0x40) \
    X(QueueCreateFailed, 0x41) \
    X(SemaphoreBinaryCreateFailed, 0x42) \
    X(MutexCreateFailed, 0x43) \
    X(TimerCreateFailed, 0x44) \
    X(EventgroupCreateFailed, 0x45) \
    X(SemaphoreCountingCreateFailed, 0x46) \
    X(MutexRecursiveCreateFailed, 0x47) \
    X(StreambufferCreateFailed, 0x49) \
    X(TimerDeleteFailed, 0x48) \
    X(SemaphoreReset, 0x6A) \
    X(SemaphoreGiveSuccess, 0x51) \
    X(SemaphoreGiveFailed, 0x54) \
    X(SemaphoreGiveBlocking, 0x57) \
    X(SemaphoreGiveFromisr, 0x5A) \
    X(SemaphoreGiveFromisrFailed, 0x5D) \
    X(SemaphoreTakeSuccess, 0x61) \
    X(SemaphoreTakeBlocking, 0x67) \
    X(SemaphoreTakeFailed, 0x64) \
    X(SemaphoreTakeFromisrFailed, 0x6D) \
    X(SemaphorePeekSuccess, 0x71) \
    X(SemaphorePeekFailed, 0x74) \
    X(SemaphorePeekBlocking, 0x77) \
    X(MutexGiveSuccess, 0x52) \
    X(MutexGiveFailed, 0x55) \
    X(MutexGiveBlocking, 0x58) \
    X(MutexTakeSuccess, 0x62) \
    X(MutexTakeFailed, 0x65) \
    X(MutexTakeBlocking, 0x68) \
    X(MutexPeekSuccess, 0x72) \
    X(MutexPeekFailed, 0x75) \
    X(MutexPeekBlocking, 0x78) \
    X(CondvarInit, 0x6F) \
    X(CondvarSignalSuccess, 0x76) \
    X(CondvarSignalBlocking, 0x79) \
    X(CondvarSignalFailure, 0x7A) \
    X(CondvarBroadcastEnter, 0x7D) \
    X(CondvarBroadcastExit, 0x7E) \
    X(CondvarWaitSuccess, 0x7F) \
    X(CondvarWaitBlocking, 0x80) \
    X(CondvarWaitFailure, 0x81) \
    X(UserEvent, 0x90) \
    X(UserEventFixed, 0x98) \
    X(TimerInit, 0xA0) \
    X(TimerStart, 0xA1) \
    X(TimerStop, 0xA2) \
    X(TimerStatusSyncAwait, 0xA3) \
    X(TimerStatusSyncExit, 0xA4) \
    X(MailboxInit, 0x1B) \
    X(MailboxMessagePutSuccess, 0xF7) \
    X(MailboxMessagePutBlocking, 0xF8) \
    X(MailboxMessagePutFailure, 0xF9) \
    X(MailboxPutSuccess, 0xD3) \
    X(MailboxPutBlocking, 0xD5) \
    X(MailboxPutFailure, 0xD4) \
    X(MailboxAsyncPutEnter, 0xD6) \
    X(MailboxAsyncPutExit, 0xF6) \
    X(MailboxGetSuccess, 0xD7) \
    X(MailboxGetBlocking, 0xD9) \
    X(MailboxGetTimeout, 0xD8) \
    X(MailboxDataGet, 0x89) \
    X(PipeInit, 0xA5) \
    X(PipeCleanupSuccess, 0xA6) \
    X(PipeCleanupBlocking, 0xF5) \
    X(PipeCleanupFailure, 0xA7) \
    X(PipeAllocInitSuccess, 0xA8) \
    X(PipeAllocInitBlocking, 0xF4) \
    X(PipeAllocInitFailure, 0xA9) \
    X(PipePutSuccess, 0xAA) \
    X(PipePutBlocking, 0xAB) \
    X(PipePutTimeout, 0xAC) \
    X(PipeGetSuccess, 0xAD) \
    X(PipeGetBlocking, 0xAE) \
    X(PipeGetTimeout, 0xAF) \
    X(PipeBlockPutEnterDeprecated, 0xDA) \
    X(PipeBlockPutExitDeprecated, 0xED) \
    X(MessagequeueInit, 0x1A) \
    X(MessagequeueAllocInitSuccess, 0x1E) \
    X(MessagequeueAllocInitBlocking, 0x6B) \
    X(MessagequeueAllocInitTimeout, 0x1F) \
    X(MessagequeueCleanupSuccess, 0xDC) \
    X(MessagequeueCleanupBlocking, 0x6C) \
    X(MessagequeueCleanupTimeout, 0xDD) \
    X(MessagequeuePutSuccess, 0xDE) \
    X(MessagequeuePutTimeout, 0xDF) \
    X(MessagequeuePutBlocking, 0xE0) \
    X(MessagequeueGetSuccess, 0xE1) \
    X(MessagequeueGetTimeout, 0xE2) \
    X(MessagequeueGetBlocking, 0xE3) \
    X(MessagequeuePeekSuccess, 0xE4) \
    X(MessagequeuePeekFailed, 0xE5) \
    X(MessagequeuePurge, 0xE6) \
    X(MemorySlabAllocSuccess, 0xE7) \
    X(MemorySlabAllocTimeout, 0xE8) \
    X(MemorySlabAllocBlocking, 0xE9) \
    X(MemorySlabAllocError, 0xEB) \
    X(MemorySlabFree, 0xEC) \
    X(KheapAlignedAllocSuccess, 0x84) \
    X(KheapAlignedAllocSuccessBlocked, 0x16B) \
    X(KheapAlignedAllocBlocking, 0x86) \
    X(KheapAlignedAllocFailure, 0x85) \
    X(KheapAllocSuccess, 0x87) \
    X(KheapAllocBlocking, 0xFA) \
    X(KheapAllocFailure, 0xFB) \
    X(KheapFree, 0x88) \
    X(KheapSysAlignedAllocSuccess, 0x50) \
    X(KheapSysAlignedAllocBlocking, 0x53) \
    X(KheapSysAlignedAllocFailure, 0x56) \
    X(KheapSysMallocSuccess, 0x59) \
    X(KheapSysMallocBlocking, 0x5C) \
    X(KheapSysMallocFailure, 0x60) \
    X(KheapSysFreeEnter, 0x63) \
    X(KheapSysFreeExit, 0x66) \
    X(KheapSysCallocSuccess, 0x69) \
    X(KheapSysCallocBlocking, 0x73) \
    X(KheapSysCallocFailure, 0x70) \
    X(HeapMalloc, 0x8A) \
    X(HeapFree, 0x8B) \
    X(HeapCalloc, 0x8C) \
    X(UnusedStack, 0xEA) \
    X(SystemSyscallEnter, 0xFE) \
    X(SystemSyscallExit, 0xFF) \
    X(TaskCreate, 0x00) \
    X(TaskReady, 0x30) \
    X(TaskPriority, 0x15F) \
    X(TaskDelete, 0x15E) \
    X(RunnableRegister, 0x167) \
    X(RunnableStart, 0x168) \
    X(RunnableStop, 0x169) \
    X(DependencyRegister, 0x16A) \
    X(StatemachineStateCreate, 0x170) \
    X(StatemachineCreate, 0x171) \
    X(StatemachineStatechange, 0x172) \
    X(IntervalCreate, 0x173) \
    X(IntervalChannelCreate, 0x174) \
    X(IntervalChannelSetCreate, 0x175) \
    X(IntervalStatechange, 0x176) \
    X(IntervalStart, 0x177) \
    X(IntervalStop, 0x178) \
    X(CounterCreate, 0x179) \
    X(CounterChange, 0x17A) \
    X(CounterLimitExceeded, 0x17B) \
    X(MallocFailed, 0x17C) \
    X(FreeFailed, 0x17D) \
    X(ExtensionCreate, 0x17E) \
    X(HeapCreate, 0x17F) \
    X(PipeReset, 0x180) \
    X(PipeClose, 0x181) \
    X(PipeWriteSuccess, 0x182) \
    X(PipeWriteBlocking, 0x183) \
    X(PipeWriteTimeout, 0x184) \
    X(PipeReadSuccess, 0x185) \
    X(PipeReadBlocking, 0x186) \
    X(PipeReadTimeout, 0x187) \
    X(Unknown, 0xFFF)
/* clang-format on */

class TraceEvent;

enum class PsfEventCode : uint16_t {
#define X(name, value) name = (value),
  EVENT_CODE()
#undef X
};

PsfEventCode GetEventFromCode(uint16_t code);
const char* GetEventName(PsfEventCode code);
}  // namespace tracealyzer

}  // namespace perfetto

#endif  // SRC_TRACED_PROBES_TRACEALYZER_TRACE_EVENT_H_
